apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: dev
# namePrefix: prefix-
# nameSuffix: -suffix
# commonLabels:
#   label1: label1-valid
# commonAnnotations:
#   annotation1: annotation1-val
images:
- name: 693440655005.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 693440655005.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: b530bf16
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
